name: Build Linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.base }}${{ matrix.suffix }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {cxx: "clang++-15", cc: "clang-15", base: "clang"}
          - {cxx: "g++-13", cc: "gcc-13", base: "gcc"}
        suffix: ["", "-onnx"]
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/deps
          key: deps-${{ runner.os }}-${{ hashfiles('dependencies.txt') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        env:
          CC: gcc-13
          CXX: g++-13
        run: |
          chmod +x .github/workflows/scripts/install_deps.sh
          ./.github/workflows/scripts/install_deps.sh

      - name: Build
        shell: bash
        env:
          BUILD_TYPE: Release
          CONFIG_TYPE: ${{ matrix.config.base }}${{ matrix.suffix }}
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          cmake --preset=$CONFIG_TYPE -DBUILD_SHARED_LIBS=OFF -DCMAKE_PREFIX_PATH=~/deps
          cd ./build
          make

      - name: Run tests
        shell: bash
        working-directory: ./build
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        run: |
          make test
