name: Build MSVC

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: ["msvc", "msvc-onnx", "msvc-onnx-dml"]

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: C:/deps
          key: deps-${{ runner.os }}-${{ hashfiles('dependencies.txt') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: powershell
        env:
          BUILD_TYPE: Release
        run: ./.github/workflows/scripts/install_deps.ps1

      - name: Build
        shell: powershell
        env:
          BUILD_TYPE: Release
          CONFIG_TYPE: ${{ matrix.config }}
        run: |
          cmake --preset=$env:CONFIG_TYPE -DBUILD_SHARED_LIBS=OFF -DCMAKE_PREFIX_PATH=C:/deps
          cd ./build
          cmake --build . --config $env:BUILD_TYPE

      - name: Run tests
        shell: powershell
        working-directory: ./build
        env:
          BUILD_TYPE: Release
        run: |
          cmake --build . --target RUN_TESTS --config $env:BUILD_TYPE
