name: Lint

on:
  workflow_call:

jobs:
  clang-format:
    name: check ${{ matrix.path['check'] }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        path:
          - check: "include"
            exclude: "(rad\\.hpp)"
          - check: "src"
            exclude: ""
          - check: "test"
            exclude: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: "3.12"

      - name: Cache virtualenv
        uses: actions/cache@v4
        with:
          key: venv_ubuntu-24.04_py-${{ steps.setup_python.outputs.python-version }}_${{ hashFiles('requirements.txt') }}
          path: venv

      - name: Install Linters
        shell: bash
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python -m pip install -r requirements.txt
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "17"
          check-path: ${{ matrix.path['check'] }}

      - name: Ruff
        shell: bash
        run: ruff check tools

      - name: Mypy
        shell: bash
        run: mypy tools
