name: MSVC

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.clang-format'
      - 'data/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.clang-format'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "MSVC Debug",
            os: windows-latest,
            build_type: "Debug",
            cc: "cl",
            cxx: "cl",
          }
        - {
            name: "MSVC Release",
            os: windows-latest,
            build_type: "Release",
            cc: "cl",
            cxx: "cl",
          }
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: rad-deps
        with:
          path: |
            C:/deps
            C:/onnxruntime
          key: ${{ env.cache-name }}-msvc-${{ matrix.config.build_type }}

      - name: Install dependencies
        shell: powershell
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
        run: |
          $c="C:/deps"
          if(-not (Test-Path $c))
          {
            git clone https://github.com/fmtlib/fmt.git --branch 9.1.0 --depth 1
            cmake -G "Visual Studio 17 2022" -S fmt -B fmt/build -DCMAKE_CXX_STANDARD=20 -DFMT_INSTALL=ON -DFMT_TEST=OFF -DCMAKE_INSTALL_PREFIX=C:/deps/fmt
            cd ./fmt/build
            cmake --build . --config $env:BUILD_TYPE
            cmake --build . --target INSTALL --config $env:BUILD_TYPE
            cd ../..

            git clone https://github.com/catchorg/Catch2.git --branch v3.3.2 --depth 1
            cmake -G "Visual Studio 17 2022" -S Catch2 -B Catch2/build -DCMAKE_CXX_STANDARD=20 -DCATCH_INSTALL_DOCS=OFF -DCMAKE_INSTALL_PREFIX=C:/deps/Catch2
            cd ./Catch2/build
            cmake --build . --config $env:BUILD_TYPE
            cmake --build . --target INSTALL --config $env:BUILD_TYPE
            cd ../..

            git clone https://github.com/oneapi-src/oneTBB.git --branch v2021.8.0 --depth 1
            cmake -G "Visual Studio 17 2022" -S oneTBB -B oneTBB/build -DCMAKE_CXX_STANDARD=20 -DTBB_TEST=OFF -DCMAKE_INSTALL_PREFIX=C:/deps/tbb
            cd ./oneTBB/build
            cmake --build . --config $env:BUILD_TYPE
            cmake --build . --target INSTALL --config $env:BUILD_TYPE
            cd ../..

            git clone https://github.com/opencv/opencv.git --branch 4.7.0 --depth 1
            cmake -G "Visual Studio 17 2022" -S opencv -B opencv/build -DCMAKE_CXX_STANDARD=20 -DBUILD_opencv_world=ON -DWITH_TBB=ON -DCMAKE_INSTALL_PREFIX=C:/deps/opencv
            cmake --build . --config $env:BUILD_TYPE
            cmake --build . --target INSTALL --config $env:BUILD_TYPE
            cd ../..
            
            wget https://github.com/microsoft/onnxruntime/releases/download/v1.14.1/onnxruntime-win-x64-1.14.1.zip -outfile onnxruntime-win-x64-11.14.1.zip
            Expand-Archive -Path onnxruntime-win-x64-1.14.1.zip -DestinationPath ./onnxruntime
            cd onnxruntime/onnxruntime-win-x65-1.14.1
            New-Item -Path C:/ -Name "onnxruntime" -ItemType Directory
          Copy-Item -Path ./* -Destination C:/onnxruntime -PassThru -Recurse
          }

      - name: Build
        shell: powershell
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
        run: |
          cmake --preset=msvc-onnx -DBUILD_SHARED_LIBS=OFF -DCMAKE_PREFIX_PATH=C:/deps
          cd ./build
          cmake --build . --config $env:BUILD_TYPE

      - name: Run tests
        shell: powershell
        working-directory: ./build
        env:
          BUILD_TYPE: ${{ matrix.config.build_type }}
        run: |
          cmake --build . --target RUN_TESTS --config $env:BUILD_TYPE
