name: Release Linux

on:
  workflow_call:

jobs:
  deploy:
    name: rad${{ matrix.suffix }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suffix: ["", "-onnx"]
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/deps
          key: deps-${{ runner.os }}-${{ hashfiles('dependencies.txt') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: bash
        env:
          CC: gcc-13
          CXX: g++-13
        run: |
          chmod +x .github/workflows/scripts/install_deps.sh
          ./.github/workflows/scripts/install_deps.sh

      - name: Build
        shell: bash
        env:
          CC: gcc-13
          CXX: g++-13
          BUILD_TYPE: Release
          CONFIG_TYPE: gcc${{ matrix.suffix }}
        run: |
          cmake --preset=$CONFIG_TYPE -DBUILD_SHARED_LIBS=OFF -DCMAKE_PREFIX_PATH=~/deps -DCMAKE_INSTALL_PREFIX=install/rad -DRAD_INSTALL_TARGET=ON
          cd ./build
          make

      - name: Run tests
        shell: bash
        working-directory: ./build
        env:
          CC: gcc-13
          CXX: g++-13
        run: make test

      - name: Install
        shell: bash
        working-directory: ./build
        env:
          CC: gcc-13
          CXX: g++-13
        run: make install

      - name: Package
        shell: bash
        working-directory: ./install
        env:
          CONFIG_TYPE: ${{ matrix.suffix }}
        run: tar cfv - rad -P | zstd > rad$CONFIG_TYPE-$GITHUB_REF_NAME-gcc-x64.tar.zst

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "./install/*.tar.zst"
          draft: true
