name: Release Windows

on:
  workflow_call:

jobs:
  deploy:
    name: rad${{ matrix.suffix }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        suffix: ["", "-onnx", "-onnx-dml"]
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: C:/deps
          key: deps-${{ runner.os }}-${{ hashfiles('dependencies.txt') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: powershell
        env:
          BUILD_TYPE: Release
        run: ./.github/workflows/scripts/install_deps.ps1

      - name: Build
        shell: powershell
        env:
          BUILD_TYPE: Release
          CONFIG_TYPE: ${{ matrix.config }}
        run: |
          cmake --preset=$env:CONFIG_TYPE -DBUILD_SHARED_LIBS=OFF -DCMAKE_PREFIX_PATH=C:/deps -DCMAKE_INSTALL_PREFIX=install/rad
          cd ./build
          cmake --build . --config $env:BUILD_TYPE

      - name: Run tests
        shell: powershell
        working-directory: ./build
        env:
          BUILD_TYPE: Release
        run: |
          cmake --build . --target RUN_TESTS --config $env:BUILD_TYPE

      - name: Install
        shell: powershell
        working-directory: ./build
        env:
          BUILD_TYPE: Release
        run: cmake --build . --target INSTALL --config $env:BUILD_TYPE

      - name: Package
        shell: powershell
        working-directory: ./install
        env:
          CONFIG_TYPE: ${{ matrix.suffix }}
        run: Compress-Archive -Path rad -DestinationPath rad$env:CONFIG_TYPE-$env:GITHUB_REF_NAME-msvc-x64.zip

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: "./install/*.zip"
          draft: true
